# Generated by Django 5.0.4 on 2024-04-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='envirementalistlist',
            fields=[
                ('envirementalistid', models.AutoField(primary_key=True, serialize=False)),
                ('envirementalistname', models.CharField(max_length=100)),
                ('envirementalistwebsite', models.URLField()),
                ('envirementalistemail', models.EmailField(max_length=254)),
                ('websiteimage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='topicname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='topictotoenvirementalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=100)),
                ('envirementalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.envirementalistlist')),
            ],
        ),
    ]
