# Generated by Django 5.0.4 on 2024-04-15 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictotoenvirementalist',
            name='topicname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.topicname'),
        ),
    ]
