# Generated by Django 5.0.4 on 2024-04-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_topictotoenvirementalist_topicname'),
    ]

    operations = [
        migrations.AddField(
            model_name='envirementalistlist',
            name='topicname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.topicname'),
        ),
        migrations.AlterField(
            model_name='topictotoenvirementalist',
            name='topicname',
            field=models.CharField(max_length=100),
        ),
    ]
