# Generated by Django 5.0.4 on 2024-04-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_envirementalistlist_topicname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envirementalistlist',
            name='envirementalistemail',
        ),
        migrations.RemoveField(
            model_name='envirementalistlist',
            name='websiteimage',
        ),
    ]
